### ISSUE TITLE
Authenticate designranch.org with MailChimp

### ISSUE THREAD

**Issue by southernroutes** [AIGA-Austin/design-ranch#8]
Authenticate designranch.org with MailChimp by modifying your domain's DNS records. These changes allow your campaigns to appear to come from designranch.org, instead of from our servers. 

DKIM: Create a CNAME record for k1._domainkey.designranch.org with this value:
dkim.mcsv.net

SPF: Create a TXT record for designranch.org with:
v=spf1 include:servers.mcsv.net ?all

**Comment by poofichu** [comment]
@southernroutes if I get you the log in information for this, could you
help me out and get er done? Mamma is swamped.
-- 
************************************************
Jessica Tremblay
512-585-2715
jessicatremblay.com

**Comment by southernroutes** [comment]
You betcha! I'll just need the designranch.org hosting account login provided I can create CNAME records there. I'm just doing some MailChimp house cleaning.

**Comment by poofichu** [comment]
You have been invited to the following event.

Title: 🤠 Design Ranch Board Meeting
When: Sun Mar 15, 2020 11am – 1pm Central Time - Chicago
Where: TBD
Calendar:  
reply@reply.github.com
Who:
     * aigaaustin.calendar@gmail.com - organizer
     * poofichu@gmail.com - creator
     *  
reply@reply.github.com

Event details:  
https://www.google.com/calendar/event?action=VIEW&eid=MGNqc2E0cTg4dWs5ZnZob2huNDE5cGRvYTQgcmVwbHkrMDA2NzFjZWRlMDhiYzVmY2QxMGJjYmI2YjhkMzE0ZGUyZTA0ZDM1MWUyODQ0MWY1OTJjZjAwMDAwMDAxMTU2NTBiZmM5MmExNjljZTBlMzJhNjJlQHJlcGx5LmdpdGh1Yi5jb20&tok=MjkjYWlnYWF1c3Rpbi5jYWxlbmRhckBnbWFpbC5jb20xYmQwZTNmZGQ1Mzc1OTI4OTg2NDdjZGRkMGNjMjJkZmMyNDcyZGVm&ctz=America%2FChicago&hl=en&es=0

Invitation from Google Calendar: https://www.google.com/calendar/

You are receiving this courtesy email at the account  
reply@reply.github.com  
because you are an attendee of this event.

To stop receiving future updates for this event, decline this event.  
Alternatively you can sign up for a Google account at  
https://www.google.com/calendar/ and control your notification settings for  
your entire calendar.

Forwarding this invitation could allow any recipient to send a response to  
the organizer and be added to the guest list, or invite others regardless  
of their own invitation status, or to modify your RSVP. Learn more at  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by poofichu** [comment]
This event has been canceled.

Title: 🤠 Design Ranch Board Meeting
Location TBD
When: Sun Mar 15, 2020 11am – 1pm Central Time - Chicago
Where: TBD
Calendar:  
reply@reply.github.com
Who:
     * aigaaustin.calendar@gmail.com - organizer
     * poofichu@gmail.com - creator


Invitation from Google Calendar: https://www.google.com/calendar/

You are receiving this courtesy email at the account  
reply@reply.github.com  
because you are an attendee of this event.

To stop receiving future updates for this event, decline this event.  
Alternatively you can sign up for a Google account at  
https://www.google.com/calendar/ and control your notification settings for  
your entire calendar.

Forwarding this invitation could allow any recipient to send a response to  
the organizer and be added to the guest list, or invite others regardless  
of their own invitation status, or to modify your RSVP. Learn more at  
https://support.google.com/calendar/answer/37135#forwarding
